targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # Generates config file for @InjectableInit
          generate_for_injectable: true
