arb-dir: lib/src/core/language/l10n/
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/src/core/language/generated
nullable-getter: false
generate: true


# flutter gen-l10n
